language: ruby
rvm:
  - '1.9'
  - '2.0'
  - jruby-19mode
  - ree
script:
- bundle exec rake build --trace
- gem install --verbose --backtrace
    ./pkg/git-duet-`ruby -I./lib -rgit/duet/version -e 'puts Git::Duet::VERSION'`.gem
- bundle exec rake spec --trace
notifications:
  email:
    recipients:
    - github+git-duet@modcloth.com
