language: ruby
env:
  global:
  - DEBUG=1
matrix:
  allow_failures:
  - rvm: jruby-19mode
rvm:
- 1.9.3
- 2.0.0
- jruby-19mode
notifications:
  email: github+git-duet@modcloth.com
deploy:
  provider: rubygems
  api_key:
    secure: aW7HYNkTGp3N8awbuJtDfko1CXBDTzElggAOQsA4p//V06Q/qH7ZTNZxPTf5/bPlmjDRgttMVv+zm3YGgb4pFdHzSWI+McLf+eI6g2I8s/Sp/GZQ2+dxH1wBqPtMhSI/Rv7R+J6GznALjKhM/PnNpPl6gsWePFbMebhKgKUvcHo=
  gem: git-duet
  on:
    tags: true
    repo: modcloth/git-duet
addons:
  code_climate:
    repo_token:
      secure: X4bw7rtQxk3461dIOxtLZEzCnEa/UZZpOSIOsGf6kWJFgps0gG9HGgOiwTfMnC9gJNo+FZ2JzTWMRRzljUh/QapL6yXSCrvwfN+bomFb35cG0kfQap+WWWhepY2d5jFytyW/hzzsItLtM7xOnNXEBlpKgS8C2OOns2sZq5goTkc=
