---
language: ruby
env:
  global:
  - DEBUG=1
matrix:
  allow_failures:
  - rvm: jruby-19mode
rvm:
- 1.9.3
- 2.0.0
- jruby-19mode
notifications:
  email:
    recipients:
    - github+git-duet@modcloth.com
