language: ruby
env:
  global:
  - DEBUG=1
rvm:
  - '1.9'
  - '2.0'
  - jruby-19mode
  - ree
script:
- bundle exec rake spec --trace
notifications:
  email:
    recipients:
    - github+git-duet@modcloth.com
